-- Ordre conseillé dans le SQL editor Supabase pour une base propre:
--
-- 1. schema.sql
-- 2. admin_api.sql
-- 3. seed_products_rdc_cdf.sql
--
-- Ne lance pas seed_products_rdc.sql si tu lances seed_products_rdc_cdf.sql.
-- Le seed CDF vide puis recree public.products et doit rester le dernier.
--
-- admin_roles_clients.sql est conserve seulement pour compatibilite.
--
-- Connexion admin:
-- email: admin@restaurant.com
-- mot de passe: admin123
